version: '3.6'
services:
  cocoa-maze-runner:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:integration-sauce-labs-cli
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      DEBUG:
      VERBOSE:
      BUILDKITE:
      BUILDKITE_PIPELINE_NAME:
      MAZE_DEVICE_FARM_USERNAME:
      MAZE_DEVICE_FARM_ACCESS_KEY:
      SAUCE_LABS_USERNAME:
      SAUCE_LABS_ACCESS_KEY:
    volumes:
      - ./features/fixtures/ios-swift-cocoapods/output:/app/build
      - ./features/:/app/features/
