env:
  LANG: "en_GB.UTF-8"

steps:
  - label: 'Trigger RN tests for all builds of our next branch'
    if: build.branch == "next"
    trigger: 'bugsnag-js'
    build:
      branch: 'next'
      message: 'Run RN tests with latest Cocoa next branch'
      env:
        BUILD_RN_WITH_LATEST_NATIVES: "true"
    async: true

  ##############################################################################
  #
  # Build
  #

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 30
    agents:
      queue: opensource-arm-mac-cocoa-12
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
      - features/fixtures/ios/output/ipa_url.txt
    commands:
      - ./features/scripts/build_and_upload_app.rb

  - label: 'ARM macOS 12 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-1
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "appium_server.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --farm=local
        --os=macos
        --os-version=12
        --app=macOSTestApp
        --order=random

  - label: 'ARM macOS 12 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-2
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "appium_server.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --farm=local
        --os=macos
        --os-version=12
        --app=macOSTestApp
        --order=random

  - label: 'ARM macOS 12 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-3
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "appium_server.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --farm=local
        --os=macos
        --os-version=12
        --app=macOSTestApp
        --order=random

  - label: 'ARM macOS 12 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-4
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "appium_server.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --farm=local
        --os=macos
        --os-version=12
        --app=macOSTestApp
        --order=random

  - label: 'ARM macOS 12 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-5
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "appium_server.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --farm=local
        --os=macos
        --os-version=12
        --app=macOSTestApp
        --order=random

