steps:

  ##############################################################################
  #
  # Barebones E2E tests
  #

  - label: 'iOS 16 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_16"
          - "--appium-version=1.21.0"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 16 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_16"
          - "--appium-version=1.21.0"
          - "--fail-fast"
          - "--exclude=features/[a-d].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner-legacy
        run: cocoa-maze-runner-legacy
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.8.0"
          - "--capabilities={\"browserstack.networkLogs\":\"true\"}"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner-legacy
        run: cocoa-maze-runner-legacy
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.8.0"
          - "--fail-fast"
          - "--exclude=features/[a-d].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
