env:
  LANG: "en_GB.UTF-8"

steps:
  - label: 'Trigger RN tests for all builds of our next branch'
    if: build.branch == "next"
    trigger: 'bugsnag-js'
    build:
      branch: 'next'
      message: 'Run RN tests with latest Cocoa next branch'
      env:
        BUILD_RN_WITH_LATEST_NATIVES: "true"
    async: true

  ##############################################################################
  #
  # Build
  #

  - label: 'examples/objective-c-ios'
    agents:
      queue: ms-arm-12-5
    commands:
      - cd examples/objective-c-ios
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-ios.xcworkspace -scheme objective-c-ios -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-ios.xcworkspace -scheme objective-c-ios -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/objective-c-osx'
    agents:
      queue: ms-arm-12-5
    commands:
      - cd examples/objective-c-osx
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-osx.xcworkspace -scheme objective-c-osx -configuration Release -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-osx.xcworkspace -scheme objective-c-osx -configuration Debug -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/swift-ios'
    agents:
      queue: ms-arm-12-5
    commands:
      - cd examples/swift-ios
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -workspace swift-ios.xcworkspace -scheme swift-ios -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -workspace swift-ios.xcworkspace -scheme swift-ios -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/swift-package-manager'
    agents:
      queue: ms-arm-12-5
    commands:
      - cd examples/swift-package-manager
      - echo "--- Resolve Swift Package Dependencies"
      - sed -i '' -e 's/kind = branch/kind = revision/' -e "s/branch = master/revision = ${BUILDKITE_COMMIT}/" swift-package-manager.xcodeproj/project.pbxproj
      - xcodebuild -allowProvisioningUpdates -scheme swift-package-manager -derivedDataPath DerivedData -resolvePackageDependencies
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -scheme swift-package-manager -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -scheme swift-package-manager -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/swiftui'
    agents:
      queue: ms-arm-12-5
    commands:
      - cd examples/swiftui
      - echo "--- Resolve Swift Package Dependencies"
      - sed -i '' -e 's/kind = branch/kind = revision/' -e "s/branch = master/revision = ${BUILDKITE_COMMIT}/" swiftui.xcodeproj/project.pbxproj
      - xcodebuild -allowProvisioningUpdates -scheme "swiftui (iOS)" -derivedDataPath DerivedData -resolvePackageDependencies
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -scheme "swiftui (iOS)" -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild  -allowProvisioningUpdates -scheme "swiftui (iOS)" -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Release macOS"
      - xcodebuild  -allowProvisioningUpdates -scheme "swiftui (macOS)" -configuration Release -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Release tvOS"
      - xcodebuild  -allowProvisioningUpdates -scheme "swiftui (tvOS)" -configuration Release -destination generic/platform=tvOS -derivedDataPath DerivedData -allowProvisioningUpdates -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug tvOS Simulator"
      - xcodebuild  -allowProvisioningUpdates -scheme "swiftui (tvOS)" -configuration Debug -destination generic/platform=tvOS\ Simulator -derivedDataPath DerivedData -allowProvisioningUpdates -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
