env:
  LANG: "en_GB.UTF-8"

steps:

  - label: 'iOS 10 E2E tests - Appium 1.7.0'
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=bs://de518c6c93bee32c8eefb9f88fdc8c2eef728428"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests - Appium 1.8.0'
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=bs://de518c6c93bee32c8eefb9f88fdc8c2eef728428"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.8.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests - Appium 1.12.1'
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=bs://de518c6c93bee32c8eefb9f88fdc8c2eef728428"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.12.1"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests - Appium 1.13.0'
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=bs://de518c6c93bee32c8eefb9f88fdc8c2eef728428"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.13.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests - Appium 1.14.0'
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=bs://de518c6c93bee32c8eefb9f88fdc8c2eef728428"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.14.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests - Appium 1.15.0'
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        upload: ["maze_output/failed/**/*"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=bs://de518c6c93bee32c8eefb9f88fdc8c2eef728428"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.15.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

