env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #

  - label: Build cocoa IPA
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa-11
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  # BrowserStack Network monitoring
  - label: 'BrowserStack network monitoring'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 40
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios/output/iOSTestApp.ipa"]
        upload: ["maze_output/**/*"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "features/network_soak.feature"
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_13"
          - "--appium-version=1.17.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
