steps:
  - label: Build cocoa IPA
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa-11
    artifact_paths:
      - features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  - label: ':ios: BrowserStack iOS 14 full end-to-end tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--resilient"
          - "--appium-version=1.17.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: Sauce-labs iOS full end-to-end tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=sl"
          - "--device=sl_ios"
          - "--resilient"
          - "--appium-version=1.17.0"
    concurrency: 2
    concurrency_group: sl-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
